name: Java bump version

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v4
      with:
        ref: development
    - name: Get latest commit message
      id: get_commit_message
      run: |
        echo "$(git log -2 --pretty=$s | tail -1)" 
        commit_message="${{ github.event.head_commit.message }}"
    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Get Release Version
      run: |
        release_version="${{steps.bump.outputs.version}}"
        echo "base_ref => ${{ github.event.base_ref }}"
        echo "before => ${{ github.event.before }}"
        echo "release_version=${release_version}" >> $GITHUB_ENV
        echo "New release version is ${{ env.release_version }}"
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Get commit message
      id: commit_message
      run: |
        echo "$(git show -s --format=%s)" 
        commit_message="${{ github.event.head_commit.message }}"
    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.release_version }}"
        release_name: "v${{ env.release_version }}"
        draft: false
        prerelease: false
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: temurin
        cache: maven
    
    - name: Build with Maven
      run: |
        current_version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        echo "Current version is $current_version"
        mvn --batch-mode --update-snapshots verify
    - name: Deploy
      run: |
        mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}