name: Java bump version

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v4
      with:
        ref: development
    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}
    - name: Get Release Version
      run: |
        release_version="${{steps.bump.outputs.version}}"
        echo "release_version=${release_version}" >> $GITHUB_ENV
        echo "New release version is ${{ env.release_version }}"
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.release_version }}"
        release_name: "v${{ env.release_version }}"
        draft: false
        prerelease: false
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots verify
        mvn -Dmaven.resolver.transport=wagon deploy
    - name: Create directory
      run: mkdir staging && cp target/*.jar staging
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging


